# Generated by Django 6.0.4 on 2026-04-09 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='Slug')),
                ('resumo', models.CharField(blank=True, max_length=255, verbose_name='Resumo')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('publicado', models.BooleanField(default=True, verbose_name='Publicado')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-criado_em'],
            },
        ),
    ]
