# Generated by Django 6.0.4 on 2026-04-10 00:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_user_post_autor_post_visualizacoes_reaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reaction',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='reaction',
            name='emoji',
            field=models.CharField(choices=[('🤩', '🤩'), ('🚀', '🚀'), ('😂', '😂'), ('👌', '👌'), ('🤖', '🤖'), ('👍', '👍'), ('👎', '👎')], default='👍', max_length=4),
        ),
        migrations.AlterUniqueTogether(
            name='reaction',
            unique_together={('post', 'user', 'emoji')},
        ),
    ]
