# Generated by Django 6.0.4 on 2026-04-07 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
